export const UserActionTypes = {
  // FETCH_USERS: 'FETCH_USERS'
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  REMOVE_USER: 'REMOVE_USER',
  USER_TO_DELETE: 'USER_TO_DELETE',
  TOGGLE_DELETE_HIDDEN: 'TOGGLE_DELETE_HIDDEN'
};